pollpy_mertkan_henden/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('polls/', include('pollpy.urls', namespace='pollpy')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_registration, name="registration"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Benutzername', max_length=25,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Benutzername'}))
    email = forms.EmailField(label='E-Mail',
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'E-Mail'}))
    password = forms.CharField(
        label='Passwort', max_length=100, min_length=5,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Passwort'}))
    password2 = forms.CharField(
        label='Passwort bestätigen', max_length=100,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Passwort bestätigen'}))

    def clean_email(self):
        """
        Überprüfen, ob E-Mail bereits verwendet wird.
        :return: email
        """
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise ValidationError(
                'E-Mail wird bereits verwendet.'
            )
        return email

    def clean_username(self):
        """
        Überprüfen, ob Benutzername bereits verwendet wird.
        :return: username
        """
        username = self.cleaned_data['username']
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise ValidationError(
                'Benutzername wird bereits verwendet.'
            )
        return username

    def clean(self):
        """
        Passwortbestätigung.
        """
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password')
        p2 = cleaned_data.get('password2')
        if p1 != p2:
            raise ValidationError(
                'Passwordbestätigung fehlgeschlagen.'

            )

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UserRegistrationForm


# Create your views here.
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,
                            username=username,
                            password=password)
        # Login und Weiterleitung zu ursprünglicher URL
        if user is not None:
            login(request, user)
            redirect_url = request.GET.get('next', 'pollpy:list')
            return redirect(redirect_url)
        else:
            messages.error(request,
                           'Ihre Anmeldedaten sind nicht richtig.',
                           extra_tags='alert alert-dismissible fade show alert-danger')
    return render(request, 'users/login.html', context={})


def user_logout(request):
    logout(request)
    return redirect('index')


def user_registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username, email=email, password=password)
            messages.success(request,
                             'Nun sind Sie ein Teil von Pollpy.',
                             extra_tags='alert alert-dismissible fade show alert-warning')
            return redirect('users:login')
    else:
        form = UserRegistrationForm()

    return render(request, 'users/register.html', {'form': form})

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-3">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Benutzername</label>
                    <input type="text" class="form-control" name="username"
                           placeholder="Ihr Benutzername">
                </div>
                <div class="form-group">
                    <label for="password">Passwort</label>
                    <input type="password" class="form-control" name="password" placeholder="Ihr Passwort">
                </div>
                <button type="submit" class="btn btn-primary">Anmelden</button>
            </form>
            <p class="mt-2">Sie haben kein Konto? <a href="{% url 'users:registration' %}">Registrieren</a></p>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-3">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}

                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Registrieren</button>
            </form>
            <p class="mt-2">Sie haben ein Konto? <a href="{% url 'users:login' %}">Anmelden</a></p>

            </div>
        </div>
    </div>
{% endblock %}