pollpy/urls.py
from django.urls import path
from . import views

app_name = "pollpy"
urlpatterns = [
    path('list/', views.polls_list, name="list"),
    path('detail/<int:poll_id>/', views.poll_detail, name="detail"),
    path('detail/<int:poll_id>/vote', views.poll_vote, name="vote"),
    path('add/', views.add_poll, name="add"),
    path('edit/poll/<int:poll_id>', views.edit_poll, name="edit_poll"),
    path('edit/choice/<int:choice_id>', views.edit_choice, name="edit_choice"),
    path('delete/poll/<int:poll_id>', views.delete_poll, name="delete_poll"),
    path('delete/choice/<int:choice_id>', views.delete_choice, name="delete_choice"),
]

pollpy_mertkan_henden/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('polls/', include('pollpy.urls', namespace='pollpy')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_registration, name="registration"),
]

pollpy/models.py
from django.contrib.auth.models import User
from django.db import models


class Poll(models.Model):
    """Model für einzelne Umfragen."""
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=1
    )
    text = models.CharField(max_length=200)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

    def only_vote_once(self, user):
        """
        Einmaliges Bewerten einer Frage ermöglichen.
        :param user:
        :return: boolean
        """
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    @property
    def participant_count(self):
        """
        Ausgabe der Teilnehmeranzahl an einer Frage.
        """
        return self.vote_set.count()

    def get_choice_results_dict(self):
        """
        Ausgabe der notwendigen Informationen
        für Visualisierung als Dictionary.
        :return:
        """
        results = []
        for choice in self.choice_set.all():
            c_dict = {}
            c_dict['choice_text'] = choice.choice_text
            c_dict['vote_count'] = choice.vote_count
            if not self.participant_count:
                c_dict['percentage'] == int(0)
            else:
                c_dict['percentage'] = int(choice.vote_count / self.participant_count * 100)
            results.append(c_dict)
        return results


class Choice(models.Model):
    """
    Model für Antwortmöglichkeiten.
    Hat eine Many-to-One-Beziehung zu Poll.
    """
    poll = models.ForeignKey(
        Poll,
        on_delete=models.CASCADE
    )
    choice_text = models.CharField(max_length=150)

    def __str__(self):
        return f"Frage: {self.poll.text[:25]} Antwort: {self.choice_text[:25]}"

    @property
    def vote_count(self):
        """
        Ausgabe der Abstimmungsanzahl für Antwort.
        """
        return self.vote_set.count()


class Vote(models.Model):
    """
    Model, um Bewertungen an Nutzer zu binden.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

pollpy/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Poll, Choice


class PollForm(forms.ModelForm):
    """
    Form für das erstellen von Fragen
    """
    choice_text1 = forms.CharField(label='Erste Antwortmöglickeit', max_length=100, min_length=2,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice_text2 = forms.CharField(label='Zweite Antwortmöglichkeit', max_length=100, min_length=2,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Poll
        fields = ['text', 'choice_text1', 'choice_text2']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 20}),
        }


class EditPollForm(forms.ModelForm):
    choice_text_add = forms.CharField(required=False, label='Weitere Antwortmöglickeiten hinzufügen', max_length=100,
                                      min_length=2, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Poll
        fields = ['text', 'choice_text_add']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'required': 'false', 'rows': 3, 'cols': 20}),
        }
        labels = {
            'text': _('Aktuelle Frage'),
        }


class EditChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', ]
        labels = {
            'choice_text':_('Aktuelle Antwort'),
        }
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', 'required': 'false', 'rows': 2, 'cols': 20,})
        }

pollpy/views.py
import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import Poll, Choice, Vote
from .forms import PollForm, EditPollForm, EditChoiceForm


# Create your views here.
@login_required()
def polls_list(request):
    """
    Übersicht über alle Fragen
    :param request:
    :return: polls_list.html
    """
    polls = Poll.objects.all()
    # Filter für die Fragenübersicht
    if 'title' in request.GET:
        polls = polls.order_by('text')
    if 'pub_date' in request.GET:
        polls = polls.order_by('-pub_date')
    if 'trends' in request.GET:
        polls = polls.annotate(Count('vote')).order_by('-vote__count')
    if 'search' in request.GET:
        searched_string = request.GET['search']
        polls = polls.filter(text__icontains=searched_string)

    # Aufteilen der Fragen in mehrere Seiten
    paginator = Paginator(polls, 5)
    page = request.GET.get('page')
    polls = paginator.get_page(page)

    dict_copy = request.GET.copy()
    parameter = dict_copy.pop('page', True) and dict_copy.urlencode()

    context = {
        'polls': polls,
        'parameter': parameter,
    }
    return render(request, 'pollpy/polls_list.html', context)


@login_required()
def add_poll(request):
    """
    Form wird eingelesen und der Titel der Frage wird gespeichert.
    Dabei wird Form nicht direkt gespeichert, um das Erstellungsdatum
    automatisch einzutragen. Daraufhin werden die Antworten gespeichert.
    Beim erstmaligen Erstellen einer Frage kann man zwei Antwortmöglichkeiten
    festlegen und anschließend unter edit_poll weitere Antworten hinzufügen.
    :param request:
    :return: add_poll.html
    """
    if request.method == 'POST':
        form = PollForm(request.POST)

        # Wenn neue Frage erstellt wird, wird das aktuelle Datum eingetragen.
        if form.is_valid():
            new_poll = form.save(commit=False)
            new_poll.pub_date = datetime.datetime.now()
            new_poll.author = request.user
            new_poll.save()
            new_choice1 = Choice(
                poll=new_poll,
                choice_text=form.cleaned_data['choice_text1']
            ).save()
            new_choice2 = Choice(
                poll=new_poll,
                choice_text=form.cleaned_data['choice_text2']
            ).save()
            messages.success(request, 'Ihre Frage wurde erstellt',
                             extra_tags='alert alert-dismissible fade show alert-warning')
            return redirect('pollpy:list')
    else:
        form = PollForm()
    context = {'form': form}
    return render(request, 'pollpy/add_poll.html', context)


@login_required()
def poll_detail(request, poll_id):
    """
    Detailansicht für Fragen, die noch nicht beantwortet wurden.
    Votingfunktion kann nur einmal genutzt werden, sodass Nutzer
    bei nächstem Seitenaufruf auf die Ergebnisseite weitergeleitet
    werden.
    :param request:
    :param poll_id:
    :return: poll_results.html
    """
    poll = get_object_or_404(Poll, id=poll_id)
    if not poll.only_vote_once(request.user):
        results = poll.get_choice_results_dict()
        return render(request, 'pollpy/poll_results.html', context={'poll': poll, 'results': results})
    else:
        only_vote_once = poll.only_vote_once(request.user)
        context = {'poll': poll, 'only_vote_once': only_vote_once}
        return render(request, 'pollpy/poll_detail.html', context)


@login_required()
def poll_vote(request, poll_id):
    """
    Überprüfungen der Votingfunktion verhindern erneutes abstimmen
    und sichert, dass eine Auswahl getroffen wurde.
    :param request:
    :param poll_id:
    :return: poll_results.html
    """
    poll = get_object_or_404(Poll, id=poll_id)

    # Verhindert erneutes Abstimmen durch only_vote_once
    if not poll.only_vote_once(request.user):
        results = poll.get_choice_results_dict()
        messages.error(request,
                       'Sie haben bereits auf diese Frage geantwortet.',
                       extra_tags='alert alert-dismissible fade show alert-warning')
        return HttpResponseRedirect(reverse('pollpy:detail', args=(poll_id,)))

    # Ausgewählter Radio-input
    choice_id = request.POST.get('choice')

    # Sichert, dass Auswahl getroffen wurde
    if choice_id:
        choice = Choice.objects.get(id=choice_id)
        vote = Vote(user=request.user, poll=poll, choice=choice)
        vote.save()
        results = poll.get_choice_results_dict()
    else:
        messages.error(request,
                       'Keine Auswahl getroffen.',
                       extra_tags='alert alert-dismissible fade show alert-warning')
        return HttpResponseRedirect(reverse('pollpy:detail', args=(poll_id,)))
    return render(request, 'pollpy/poll_results.html', context={'poll': poll, 'results': results})


@login_required()
def edit_poll(request, poll_id):
    """
    Nachträgliches bearbeiten nur durch den Autor
    (bzw. Admin im Adminbereich) der Frage möglich.
    :param request:
    :param poll_id:
    :return: edit_poll.html
    """
    poll = get_object_or_404(Poll, id=poll_id)

    # Überprüfen ob angemeldeter Nutzer der Autor ist
    if request.user != poll.author:
        return redirect('index')

    """
    Fragentitel wird immer gespeichert und zusätzliche 
    Antwortmöglichkeit nur bei Bedarf
    """
    if request.method == "POST":
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid():
            form.save()
            new_choice = Choice(
                poll=poll,
                choice_text=form.cleaned_data['choice_text_add']
            )
            if new_choice.choice_text != '':
                new_choice.save()
            messages.success(request, 'Ihre Frage wurde bearbeitet.',
                            extra_tags='alert alert-dismissible fade show alert-warning')
    else:
        form = EditPollForm(instance=poll)
        context = {'form': form}
    return render(request, 'pollpy/edit_poll.html', {'form': form, 'poll':poll})


@login_required()
def edit_choice(request, choice_id):
    """
    Verändern einer Antwortmöglickeit durch den Autor.
    :param request:
    :param choice_id:
    :return: edit_poll.html
    """
    choice = get_object_or_404(Choice, id=choice_id)

    if request.user != choice.poll.author:
        return redirect('index')

    if request.method == "POST":
        form = EditChoiceForm(request.POST, instance=choice)
        if form.is_valid():
            form.save()
        messages.success(request, 'Ihre Antwort wurde bearbeitet.',
                         extra_tags='alert alert-dismissible fade show alert-warning')
        return HttpResponseRedirect(reverse('pollpy:edit_poll', args=(choice.poll.id,)))
    else:
        form = EditChoiceForm(instance=choice)
    return render(request, 'pollpy/edit_choice.html', {'form':form, 'choice': choice})


@login_required()
def delete_choice(request, choice_id):
    """Löschfunktion für Antwortmöglichkeiten."""
    choice = get_object_or_404(Choice, id=choice_id)

    if request.user != choice.poll.author:
        return redirect('index')

    else:
        choice.delete()
        messages.success(request, 'Die ausgewählte Antwort wurde gelöscht.',
                         extra_tags='alert alert-dismissible fade show alert-success')
        return HttpResponseRedirect(reverse('pollpy:edit_poll', args=(choice.poll.id,)))


def delete_poll(request, poll_id):
    """Löschfunktion für Fragen"""
    poll = get_object_or_404(Poll, id=poll_id)

    if request.user != poll.author:
        return redirect('index')

    else:
        poll.delete()
        messages.success(request, 'Die ausgewählte Frage wurde gelöscht.',
                         extra_tags='alert alert-dismissible fade show alert-success')
        return redirect('pollpy:list')

pollpy/templates/pollpy/add_poll.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-3">
                <h1>Was möchten Sie wisssen?</h1>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Frage erstellen</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

pollpy/templates/pollpy/edit_choice.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 mt-3">
                <h1>{{ choice.poll }}</h1>
                <hr>

                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit"
                            class="btn btn-primary">
                        Antwort bearbeiten</button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

pollpy/templates/pollpy/edit_poll.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 mt-3">
                <h1>{{ poll }}</h1>
                <hr>
                <div class="mb-3">

                    <button class="btn btn-light btn-lg btn-block type="button" data-toggle="collapse"
                            data-target="#poll_edit_collapse" aria-expanded="false"
                            aria-controls="collapseExample">Bisherige Antworten
                    </button>

                    <div class="collapse" id="poll_edit_collapse">
                        <div class="card card-body">
                            {% for choice in poll.choice_set.all%}
                                <ul class="list-group list-group-flush">

                                    <li class="list-group-item">{{ choice.choice_text }}
                                     <a href="{% url 'pollpy:delete_choice' choice.id %}"
                                        class="btn btn-danger btn-sm float-right ml-1"
                                        onclick="return confirm('Möchten Sie wirklich die Antwort löschen?');">Löschen</a>
                                     <a href="{% url 'pollpy:edit_choice' choice.id %}"
                                        class="btn btn-info btn-sm float-right">✎ Bearbeiten</a>
                                    </li>
                                </ul>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}

                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Frage bearbeiten</button>
                                <a href="{% url 'pollpy:delete_poll' poll.id %}"
                   class="btn btn-danger ml-1"
                   onclick="return confirm('Damit werden auch alle dazugehörigen Fragen gelöscht.');">Frage löschen</a>
                </form>


            </div>
        </div>
    </div>
{% endblock %}

pollpy/templates/pollpy/poll_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col mt-3">
                <h1>{{ poll }}</h1>
                <hr>
                <div class="card mt-3">
                    <h5 class="card-header">Wie lautet Ihre Antwort auf diese Frage?</h5>
                    <div class="card-body">
                    <form action="{% url 'pollpy:vote' poll.id %}" method="post">
                    {% csrf_token %}
                    {% for choice in poll.choice_set.all%}


                        <label for="choice {{ forloop.counter }}" class="radio-choice-vote">{{ choice.choice_text }}
                          <input type="radio" class="radio-choice-vote" name="choice"
                               id="choice {{ forloop.counter }}"
                               value="{{ choice.id }}">
                          <span class="checkmark"></span>
                        </label>
                    {% endfor %}
                    <input type="submit" value="Beantworten" class="btn btn-primary"
                           {% if not only_vote_once %}disabled{% endif %}>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pollpy/templates/pollpy/poll_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col mt-3">
                <h1>{{ poll }}</h1>
                <div class="card mt-3">
                <h5 class="card-header">{{ poll.participant_count }} Teilnehmer</h5>
                <div class="card-body">
                    {% for choice_result in results%}
                        <h5 class="card-title">{{ choice_result.choice_text }} - Stimmen: {{ choice_result.vote_count }}</h5>
                        <div class="progress mb-3" style="height: 30px;">
                        <div class="progress-bar bg-info" role="progressbar"
                             style="width:{{choice_result.percentage}}%; font-size:20px">{{ choice_result.percentage }}%</div>
                        </div>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pollpy/templates/pollpy/polls_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col mt-3">
                <h1>Pollpy entdecken</h1>
                <hr>

                <ul class="nav justify-content-end">
                  <li>
                      <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2"
                               type="search"
                               placeholder="Ihre Frage finden"
                               aria-label="Search"
                               name="search"
                                value="{{ request.GET.search }}">
                        <button class="btn btn-outline-success my-2 my-sm-0"
                                type="submit">Suchen</button>
                      </form>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if 'title' in request.GET %}disabled{% endif %}"
                      href="?title">A-Z</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if 'pub_date' in request.GET %}disabled{% endif %}"
                       href="?pub_date">Datum</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if 'trends' in request.GET %}disabled{% endif %}"
                       href="?trends">Trends</a>
                  </li>
                  <li class="nav-item">
                     <a href="{% url 'pollpy:add' %}"
                        class="btn btn-primary">Frage erstellen</a>
                  </li>
                </ul>

                {% for poll in polls%}

                <div class="card mt-3">
                    <h5 class="card-header bg-dark text-white">
                        {{ poll.text }}
                        {% if request.user == poll.author %}
                            <a href="{% url 'pollpy:edit_poll' poll.id %}"
                               class="btn btn-info btn-sm float-right">✎ Bearbeiten</a>
                        {% endif %}
                    </h5>
                    <a href="{% url 'pollpy:detail' poll.id %}" style="text-decoration: none; color: black;">
                        <div class="card-body" id="poll_list_card">
                            <p class="card-text">Erstellt von: {{ poll.author }} am {{ poll.pub_date }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
                <nav aria-label="Page navigation">
                  <ul class="pagination justify-content-center mt-3">
                  {% if polls.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1&{{ parameter }}" tabindex="-1">Erste</a>
                    </li>
                  {% endif %}

                  {% for num in polls.paginator.page_range %}
                      {% if num == polls.number %}
                          <li class="page-item" disabled><a class="page-link">{{ num }}</a></li>
                      {% elif  num > polls.number|add:'-2' and num < polls.number|add:'2' %}
                          <li class="page-item"><a class="page-link" href="?page={{ num }}&{{ parameter }}">{{ num }}</a></li>
                      {% endif %}
                  {% endfor %}

                  {% if polls.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ polls.paginator.num_pages }}&{{ parameter }}">Letzte</a></li>
                  {% endif %}
                  </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}