pollpy/urls.py
from django.urls import path
from . import views

app_name = "pollpy"
urlpatterns = [
    path('list/', views.polls_list, name="list"),
    path('detail/<int:poll_id>/', views.poll_detail, name="detail"),
    path('detail/<int:poll_id>/vote', views.poll_vote, name="vote"),
    path('add/', views.add_poll, name="add"),
    path('edit/poll/<int:poll_id>', views.edit_poll, name="edit_poll"),
    path('edit/choice/<int:choice_id>', views.edit_choice, name="edit_choice"),
    path('delete/poll/<int:poll_id>', views.delete_poll, name="delete_poll"),
    path('delete/choice/<int:choice_id>', views.delete_choice, name="delete_choice"),
]

pollpy_mertkan_henden/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('polls/', include('pollpy.urls', namespace='pollpy')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_registration, name="registration"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pollpy</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css">
</head>
<body style="text-shadow: 0 0.05rem 0.1rem rgba(0, 0, 0, 0.17);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">Pollpy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarNav" aria-controls="navbarNav"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Start<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pollpy:list' %}">Entdecken</a>
          </li>
        </ul>
        <div class="navbar-nav ml-auto">
          <li class="nav-item">
              {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              {% else %}
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              {% endif %}
          </li>
        </div>
      </div>
    </nav>

        {% if messages %}
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}


    {% block content %}
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}


    <section class="mt-5 mb-5 pt-5 pb-5 text-white" id="pollpy_index">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div id="index_content">
                        <h1 style="font-size: 85px">Pollpy</h1>
                        <p class="lead">Antworten zu unterschiedlichsten Fragen erhalten.</p>
                        <a href="{% url 'pollpy:list' %}" class="btn btn-success">Loslegen</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="bg-secondary text-white mt-5 mb-5 pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>Ihre Stimme zählt</h2>
              <p class="lead">Jeder kann bei uns Fragen stellen,
                  die unsere Community in kürzester Zeit beantwortet.
                  Sie finden bei uns Fragen zu (fast) allen Themen.</p>
            </div>
          </div>
        </div>
    </section>

    <section class="bg-light mt-5 mb-5 pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>Über Pollpy</h2>
              <p class="lead">Pollpy ist eine Frage-Antwort-Plattform.
                  Wir bringen Menschen zusammen und eröffnen Ihnen neue Perspektiven.
                  Bei uns können Sie Wissen, Erfahrung und Meinungen mit anderen teilen
                  und entdecken. Pollpy steht für einen persönlichen und offenen
                  Austausch untereinander – zu jeder Zeit und überall.
                  So entsteht eine große Themen- und Meinungsvielfalt.</p>
            </div>
          </div>
        </div>
    </section>

    <section class="bg- mt-5 mb-5 pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>Fragen und Antworten!</h2>
              <p class="lead">Erhalte ein Meinungsbild über deine Frage in wenigen Minuten.</p>
            </div>
          </div>
        </div>
    </section>
{% endblock %}